#! /usr/bin/env ruby

require "yaml"

toc = ""

YAML.load_file("_data/navigation.yml")["styles"].each do |nav_item|
  toc << " - [#{nav_item["title"]}](#{nav_item["url"]})\n"
  nav_item["children"].each do |item_child|
    toc << "   - [#{item_child["title"]}](#{item_child["url"]})\n"
  end
end

full_page = "🖌️ BASH Style Guide\n"
full_page += `cat _pages/index.md | tail +8`
full_page.sub!('<!-- TOC -->', toc)

File.write "README.md", full_page